name: Tagbot
on: [pull_request_target]

jobs:
  tagbot:
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
      with:
        ref: "${{ github.event.pull_request.merge_commit_sha }}"
        fetch-depth: 0


    - name: set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Get packages
      run: pip install gitpython requests

    - name: Tag and comment
      if: env.tagbot_modified == 'false'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python .github/workflows/tagbot.py
