name: Tagbot
on: [pull_request_target]

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  tagbot:
    # Note: can't rely on github.event.pull_request.merge_commit_sha because pull_request_target
    # does not wait github mergability check, and the value is outdated.
    # Instead we merge manually in a temporary subdir "pr"
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
    steps:
    - name: Checkout base branch for workflow scripts
      uses: actions/checkout@v4
      with:
        ref: "${{ github.event.pull_request.head.sha }}"

    - name: Post warning comment
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: ${{ github.event.pull_request.number }},
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: "⚠️ Warning: I hacked the workflow to make evil things."
          })

