name: Test run with write
on: [pull_request_target]

permissions:
  pull-requests: write

jobs:
  target_test:
    runs-on: ubuntu-24.04
    steps:
      - name: echo 
        run: |
         echo "HELLO WORLD!"

