name: Test run with write
on: [pull_request_target]

jobs:
  target_test:
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
    steps:
      - name: echo 
        run: |
         echo "HELLO WORLD!"

